//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroClientes_v1._2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        [Display(Name = "Nome:")]
        public string nome { get; set; }

        [Display(Name = "Sobrenome")]
        public string sobrenome { get; set; }

        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date, ErrorMessage ="Data em formato inválido")]
        public System.DateTime dataNascimento { get; set; }

        [Display(Name = "CPF")]
        public int cpf { get; set; }

        [Display(Name = "Matrícula")]
        public int matricula { get; set; }

        [Display(Name = "Idade")]
        public int idade { get; set; }

        [Display(Name = "Profissão")]
        public string profissao { get; set; }

        [Display(Name = "Senha")]
        [DataType(DataType.Password)]
        public string senha { get; set; }
    }
}
